language: r
dist: xenial

matrix:
  include:
  - r: devel
    env: ggplot='CRAN'
    after_success:
    - nvm install stable
    - npm install netlify-cli -g
    deploy:
      provider: script
      script: netlify deploy --prod --dir _book --message "$DEPLOY_MSG"
      skip_cleanup: true

cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    
latex: false
branches:
  only:
    - master
    - release
    - stable

pandoc_version: 2.3.1

git:
  depth: 5
  submodules: false
  
repos:
  CRAN: https://cloud.r-project.org

addons:
  apt:
    sources:
      - sourceline: ppa:opencpu/imagemagick
      - sourceline: ppa:opencpu/poppler
      - sourceline: ppa:opencpu/libgit2
      - sourceline: ppa:jonathonf/ffmpeg-3
    packages:
      - ghostscript
      - imagemagick
      - optipng
      # Rgraphviz igraph
      - graphviz
      # git2r
      - libgit2-dev
      # v8
      - libv8-dev
      # av
      - libavfilter-dev
      # gifski
      - cargo
      # for sf rgdal
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      # for odbc
      - odbc-postgresql
      # magick
      - libmagick++-dev
      # pdftools for tikz
      - libpoppler-cpp-dev
      - python3-pip
      - python3-virtualenv
      - python3-tk      

before_install:
  - virtualenv -p /usr/bin/python3 /opt/pyenv/r-tensorflow
  - source /opt/pyenv/r-tensorflow/bin/activate
  - pip install --upgrade pip
  - pip install numpy matplotlib
  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.name/tinytex.tar.gz
  - tar -xzf /tmp/tinytex.tar.gz -C $HOME
  - export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH
  - tlmgr install $(cat latex/TeXLive.pkgs | tr '\n' ' ') || true
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - echo $COMMIT_MSG
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
  - echo $DEPLOY_MSG
  - chmod +x ./_deploy.sh
  
before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'
